on armor change:
    if custom model data of event-item is 56:
        while custom model data of boots of player is 56:
            wait 5 tick
            apply jump boost 4 without particles to player for 1 second replacing existing effect
            if player is wet:
                apply slowness 4 without particles to player for 6 second replacing existing effect
                damage player by 1
